### ISSUE TITLE
Reverse  execution order of  of hive queries in Hive Monad 

### ISSUE THREAD

**Issue by kaspintonus** [CommBank/ebenezer#78]
When Hive queries are given as list 
list(a,b,c) where intended execution sequence is a>b>c. 
But monad is performing c>b>a

**Comment by SamRoberts** [comment]
This affects `Hive.queries`.

I believe this is an issue with the use of traverse and Result in Hive.queries. Traverse should guarantee that the monadic actions are run in order, but it shouldn't necessarily guarantee that the function that constructs the monadic actions are run in the same order. We do our hive queries in the function that constructs the Results, rather than in the Result itself. Therefore, we have no guarantee that the hive queries are run in order.

Some quick experiments in the console show that traverse calls the traversal functions in different orders for different monads:
```
scala> List(1,2,3).traverse(i => { println(s"in func: $i"); List(i) })
in func: 3
in func: 2
in func: 1
res6: List[List[Int]] = List(List(1, 2, 3))

scala> List(1,2,3).traverse(i => { println(s"in func: $i"); IO(i) }).unsafePerformIO
in func: 1
in func: 2
in func: 3
res7: List[Int] = List(1, 2, 3)
```
